In [2]:
scores = [56, 89, 80]
new_scores = []

for score in scores:
    new_scores.append(score + 3)

new_scores

[59, 92, 83]

In [3]:
#list comprehention(快速建立list)
scores = [78, 89, 90]
new_scores = [score+3 for score in scores]
new_scores

[81, 92, 93]

In [4]:
scores = [78, 69, 65]
scores * 2

[78, 69, 65, 78, 69, 65]

In [5]:
[67, 92, 85] + [78, 69, 65]

[67, 92, 85, 78, 69, 65]

In [6]:
import numpy as np

scores = np.array([78, 69, 65])
print(type(scores))
scores + 3

<class 'numpy.ndarray'>


array([81, 72, 68])

In [7]:
scores.sum()
scores.mean()
scores.std()
scores.min()
scores.max()
np.median(scores)

np.float64(69.0)

In [ ]:
import numpy as np
students = np.array([[67,89,90],[60,58,80],[38,59,99]]) #array是二維陣列
students

array([[67, 89, 90],
       [60, 58, 80],
       [38, 59, 99]])

In [ ]:
#常用的查詢屬性
students.ndim, #維度
students.size, #元素數量
students.shape, #列數與欄數
students.dtype #資料型態,64為位元數

(2, 9, (3, 3), dtype('int64'))

In [12]:
students[0,0] #取得第一列第一欄的值

np.int64(67)

In [ ]:
#第1位學生分數
students[0,:] #[列,欄],:表示從最前面到最後面

array([67, 89, 90])

In [ ]:
#前2個學生
students[0:2,:] #包含0,不包含2

array([[67, 89, 90],
       [60, 58, 80]])

In [ ]:
#最後2個學生
students[-2:] + 3 #倒數算起的正列運算

array([[ 63,  61,  83],
       [ 41,  62, 102]])

In [16]:
#國文
students[:,0]

array([67, 60, 38])

In [17]:
students[:,:2] #所有學生的前2科

array([[67, 89],
       [60, 58],
       [38, 59]])

In [ ]:
students[0,0] = 100 #修改第1位學生的國文成績
students

array([[100,  89,  90],
       [ 60,  58,  80],
       [ 38,  59,  99]])

In [ ]:
students[0,0] -= 10 #減10分
students

array([[90, 89, 90],
       [60, 58, 80],
       [38, 59, 99]])

In [ ]:
import pandas as pd #用pandas建立DataFrame,來生成實體表格
pd.DataFrame(data=students,index=['stu1','stu2','stu3'],columns=['國文','英文','數學'])  

國文  英文  數學
stu1  90  89  90
stu2  60  58  80
stu3  38  59  99

In [22]:
data = np.random.randint(50,high=101,size=(50,5))
students = pd.DataFrame(data,columns=['國文','英文','數學','自然','社會'])
students

國文  英文   數學  自然   社會
0   100  85   68  97   96
1    61  77   87  83   77
2    80  96   81  92   96
3    68  80   56  53   87
4    65  95   64  64   68
5    77  93   95  70   94
6    65  79   78  87   86
7    60  76   52  97   88
8    85  78   86  72   76
9    74  61   55  71   55
10   57  61   65  75   77
11   91  52   98  73   71
12   67  53   63  83   65
13   77  53   63  99   72
14   88  88   55  94   85
15   70  58   58  70   65
16   64  59   51  84   64
17   87  90   87  79   83
18   99  93   82  72   65
19   97  54   88  53   87
20   81  99   74  72   58
21   64  87   50  85   84
22   82  52   74  76   57
23   81  80   64  65   54
24   76  67   68  70   97
25   98  94   97  50   91
26   54  95   91  78   92
27   56  78   64  99   76
28   81  52   91  76   87
29   58  63   66  95   54
30   62  65   80  68   88
31   83  80   82  79   88
32   85  51   58  68   98
33   79  64   70  89   78
34   77  50   71  78   81
35   81  90   65  80   58
36   61  82   66  64   83
37   64  70   79  82   78
38   67  87   52  66   92
39   96  61   66  67   95
40   77  50   74  54   63
41   71  65  100  74   53
42  100  64   70  93   82
43   66  76   59  58   51
44   54  85   53  73   65
45   78  71   51  73   62
46   53  83   87  72   57
47   95  50   60  92   89
48   96  67   83  98   78
49   73  86   91  60  100