In [2]:
scores = [56, 89, 80]
new_scores = []

for score in scores:
    new_scores.append(score + 3)

new_scores

[59, 92, 83]

In [3]:
#list comprehention(快速建立list)
scores = [78, 89, 90]
new_scores = [score+3 for score in scores]
new_scores

[81, 92, 93]

In [4]:
scores = [78, 69, 65]
scores * 2

[78, 69, 65, 78, 69, 65]

In [5]:
[67, 92, 85] + [78, 69, 65]

[67, 92, 85, 78, 69, 65]

In [6]:
import numpy as np

scores = np.array([78, 69, 65])
print(type(scores))
scores + 3

<class 'numpy.ndarray'>


array([81, 72, 68])

In [7]:
scores.sum()
scores.mean()
scores.std()
scores.min()
scores.max()
np.median(scores)

np.float64(69.0)

In [ ]:
import numpy as np
students = np.array([[67,89,90],[60,58,80],[38,59,99]]) #array是二維陣列
students

array([[67, 89, 90],
       [60, 58, 80],
       [38, 59, 99]])

In [ ]:
#常用的查詢屬性
students.ndim, #維度
students.size, #元素數量
students.shape, #列數與欄數
students.dtype #資料型態,64為位元數

(2, 9, (3, 3), dtype('int64'))

In [12]:
students[0,0] #取得第一列第一欄的值

np.int64(67)

In [ ]:
#第1位學生分數
students[0,:] #[列,欄],:表示從最前面到最後面

array([67, 89, 90])

In [ ]:
#前2個學生
students[0:2,:] #包含0,不包含2

array([[67, 89, 90],
       [60, 58, 80]])

In [ ]:
#最後2個學生
students[-2:] + 3 #倒數算起的正列運算

array([[ 63,  61,  83],
       [ 41,  62, 102]])

In [16]:
#國文
students[:,0]

array([67, 60, 38])

In [17]:
students[:,:2] #所有學生的前2科

array([[67, 89],
       [60, 58],
       [38, 59]])

In [ ]:
students[0,0] = 100 #修改第1位學生的國文成績
students

array([[100,  89,  90],
       [ 60,  58,  80],
       [ 38,  59,  99]])

In [ ]:
students[0,0] -= 10 #減10分
students

array([[90, 89, 90],
       [60, 58, 80],
       [38, 59, 99]])

In [ ]:
import pandas as pd #用pandas建立DataFrame,來生成實體表格
pd.DataFrame(data=students,index=['stu1','stu2','stu3'],columns=['國文','英文','數學'])  

國文  英文  數學
stu1  90  89  90
stu2  60  58  80
stu3  38  59  99

In [ ]:
import random
def get_names(nums:int=10)->list: #自訂Function,default值為10
    with open('names.txt',encoding='utf-8') as file: #打開檔案
        content = file.read() #讀取檔案內容
        names = content.split('\n') #以換行符號分割
        random_names = random.sample(names,nums) #隨機取出nums個名字，且不重複(使用sample)

    return random_names #結束函數回傳資料

get_names(5)

['周琬婷', '劉昀天', '李蓉瑞', '高俊男', '陳信宏']

In [ ]:
student_nums = 10 #設定變數
data = np.random.randint(50,high=101,size=(student_nums,5)) #隨機產生50-100之間的數字，取student_nums的人數，五個欄位
students = pd.DataFrame(data,
                        columns=['國文','英文','數學','自然','社會'],
                        index = get_names(student_nums)) #columns為欄位名稱，index為列名稱

students

國文  英文  數學  自然  社會
王泓泰   70  68  70  94  55
洪阿惠   66  54  50  85  94
趙家豪   53  99  89  99  80
陳姵彬   73  57  59  51  79
葉志峰   93  58  87  51  70
張俊傑   80  98  75  61  88
呂傑宣   98  80  93  66  94
陳樂紫  100  91  71  62  73
陳逸凡   85  58  81  72  80
張天亨   55  79  91  86  50